# Server Cont Profile
aws.access-key-id=YOUR_DEV_ACCESS_KEY
aws.secret-access-key=YOUR_DEV_SECRET_KEY
aws.region=us-east-1
aws.s3.bucket-name=your-dev-bucket

# Debug logging
logging.level.com.videoupload=DEBUG
logging.level.software.amazon.awssdk=DEBUG
logging.level.org.springframework.web=DEBUG